version: '3'
services:
  database:
    container_name: database
    build:
      context: ./db/
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  backfront:
    container_name: backfront
    build:
      context: ./app/
    ports:
      - "80:5000"
      
volumes:
  db_data:
