version: '3'
services:
  database:
    container_name: database
    build:
      context: ./database/
    ports:
      - "3306:3306"
  backfront:
    container_name: backfront
    build:
      context: ./app/
    ports:
      - "80:5000"
 